Issue #1 feat: Versioning Js files added with joomla custom tag method
techjoomla/deploy-tools pull request #2
Opened 2017-10-02 14:47 UTC by lakhanmandloi

2017-10-02 14:48 UTC, lakhanmandloi commented
Fixed by Sudhir. PR Sent by Lakhan.

2017-10-02 14:51 UTC, lakhanmandloi commented
@coolbung Pls review this.

2017-10-02 16:27 UTC, coolbung requested changes
Why deal with only .min.js you should handle all js. Also, I guess it's possible to add CSS also via custom tag right ?

2017-10-03 05:42 UTC, lakhanmandloi commented
@coolbung Hi, Changes made. Can you pls review it.?

2017-10-03 05:53 UTC, coolbung commented on deploytools.php
> +			}
- PHPCS missing
- Improve code readability. See if you can reduce use of variables

2017-10-03 10:56 UTC, lakhanmandloi commented
@coolbung Hello Sir, PHPCS fixes done. Can you pls review it ?

2017-10-03 11:22 UTC, merged